### ISSUE TITLE
New Demo address?

### ISSUE THREAD

**Issue by DrSouil** [lingchen42/illustrAItion#1]
Just found the demo address "http://www.illustraition.net/" was not available. Is there a new address of it?

**Comment by lingchen42** [comment]
Dear DrSouil,

Thanks for the interest in this project. I've shut down the demo server. But if you clone the project, it should be easy to run locally as well. 
more specifically run the following after cloning the project:

cd frontend
npm install
npm start

Best,
Ling

**Comment by DrSouil** [comment]
Sorry to bother, I tried to run it. Errors in Chrome console below:

index.js:27 GET http://127.0.0.1:8000/api/dog net::ERR_CONNECTION_REFUSED
App._this.handleKeyPress @ index.js:27
callCallback @ react-dom.development.js:147
invokeGuardedCallbackDev @ react-dom.development.js:196
invokeGuardedCallback @ react-dom.development.js:250
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:265
executeDispatch @ react-dom.development.js:622
executeDispatchesInOrder @ react-dom.development.js:647
executeDispatchesAndRelease @ react-dom.development.js:747
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:760
forEachAccumulated @ react-dom.development.js:727
runEventsInBatch @ react-dom.development.js:903
runExtractedEventsInBatch @ react-dom.development.js:913
handleTopLevel @ react-dom.development.js:5078
batchedUpdates$1 @ react-dom.development.js:19041
batchedUpdates @ react-dom.development.js:2307
dispatchEvent @ react-dom.development.js:5158
interactiveUpdates$1 @ react-dom.development.js:19103
interactiveUpdates @ react-dom.development.js:2328
dispatchInteractiveEvent @ react-dom.development.js:5134
localhost/:1 Uncaught (in promise) TypeError: Failed to fetch
Promise.then (async)
App._this.handleKeyPress @ index.js:28
callCallback @ react-dom.development.js:147
invokeGuardedCallbackDev @ react-dom.development.js:196
invokeGuardedCallback @ react-dom.development.js:250
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:265
executeDispatch @ react-dom.development.js:622
executeDispatchesInOrder @ react-dom.development.js:647
executeDispatchesAndRelease @ react-dom.development.js:747
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:760
forEachAccumulated @ react-dom.development.js:727
runEventsInBatch @ react-dom.development.js:903
runExtractedEventsInBatch @ react-dom.development.js:913
handleTopLevel @ react-dom.development.js:5078
batchedUpdates$1 @ react-dom.development.js:19041
batchedUpdates @ react-dom.development.js:2307
dispatchEvent @ react-dom.development.js:5158
interactiveUpdates$1 @ react-dom.development.js:19103
interactiveUpdates @ react-dom.development.js:2328
dispatchInteractiveEvent @ react-dom.development.js:5134

**Comment by lingchen42** [comment]
Dear DrSouil,

Sorry that I wasn't clear. The previous instructions only set up the frontend. To use the backend database, you'll also need to set up the environment for running the backend database. Check here for more instructions ( https://github.com/lingchen42/illustrAItion#install-locally ).

**Comment by DrSouil** [comment]
# activate the environment
source activate illustraition

“Could not find conda environment: illustraition”

**Comment by lingchen42** [comment]
This might be due to the failure of creating the virtual conda environment illustraition. I removed the potential problem en-core-web-sm==2.0.0 package from conda environment.yml file.  Could you try pull the new changes and run through the commands again?

**Comment by DrSouil** [comment]
Sorry still the same issue.

**Comment by lingchen42** [comment]
Can you provide the log of  this step (`conda env create -f environment.yml`) ?

**Comment by DrSouil** [comment]
Solving environment: failed

ResolvePackageNotFound:
  - cymem==2.0.2=py37h04f5b5a_0
  - python==3.7.2=haf84260_0
  - openssl==1.1.1a=h1de35cc_0
  - ncurses==6.1=h0a44026_1
  - numpy==1.15.4=py37h6a91979_0
  - libedit==3.1.20181209=hb402a30_0
  - numpy-base==1.15.4=py37h8a80b8c_0
  - gensim==3.4.0=py37h1de35cc_0
  - preshed==2.0.1=py37h0a44026_0
  - murmurhash==1.0.1=py37h0a44026_0
  - xz==5.2.4=h1de35cc_4
  - scipy==1.1.0=py37h28f7352_1
  - sqlite==3.26.0=ha441bb4_0
  - zlib==1.2.11=h1de35cc_3
  - tk==8.6.8=ha441bb4_0
  - mkl_fft==1.0.6=py37hb8a8100_0
  - libgfortran==3.0.1=h93005f0_2
  - cffi==1.11.5=py37h6174b99_1
  - readline==7.0=h1de35cc_5
  - spacy==2.0.16=py37h6440ff4_0
  - libffi==3.2.1=h475c297_4
  - libcxxabi==4.0.1=hcfea43d_1
  - wrapt==1.10.11=py37h1de35cc_2
  - regex==2018.11.22=py37h1de35cc_0
  - ujson==1.35=py37h1de35cc_0
  - mkl_random==1.0.1=py37h5d10147_1
  - libcxx==4.0.1=hcfea43d_1
  - msgpack-python==0.6.1=py37h04f5b5a_1
  - thinc==6.12.1=py37h4f467ca_0
  - cytoolz==0.9.0.1=py37h1de35cc_1
  - cryptography==2.5=py37ha12b0ac_0

**Comment by lingchen42** [comment]
You might try install the python packages required for backend manually. They are
```
django
djangorestframework
django-cors-headers
numpy
spacy
translate
nltk
gensim
pattern
```
